### ISSUE TITLE
could not compile: Makefile:23: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by RoPe93** [gkdr/libomemo#1]
I only ran 'make' and it gives:
Makefile:23: *** missing separator.  Stop.

**Comment by gkdr** [comment]
Two things:
* There was no 'all' target, and I don't know what make usually does in this case. My version of make just ran the first target, creating the build dir.
* There were in fact tabs missing, but my version of make did not complain about it, even when working the referenced faulty target.
So, thanks for telling me. I actually wonder why make didn't complain.

I fixed this in c11e86ee3e7a2703af9532e905183f715ee2b703.

(Just in case you are trying to build [lurch](https://github.com/gkdr/lurch): Its makefile should call this one anyway.)
