### ISSUE TITLE
License info in each source file

### ISSUE THREAD

**Issue by tehnick** [gkdr/libomemo#11]
Please add license info into all *.c and *.h files. This is recommended by FSF, for example. And this practice is widely used in FOSS.

**Comment by gkdr** [comment]
The problem I have with this is a bit stupid - as said in the other thread, I need to use exactly the same license as libsignal-protocol-c, which is GPLv3, and NOT GPLv3+.
I could not find the header to use which does not include the "or later" clause, do you know if I can simply delete that part of the header and still use it?

**Comment by bashrc** [comment]
The headers text comes from the main LICENSE file. I think it's also possible to leave the "or later" off to peg it to a specific license version.

**Comment by tehnick** [comment]
> do you know if I can simply delete that part of the header and still use it?

Yes, sure, if you really need it. Just do not forget to use appropriate LICENSE file in this case.
But FSF strongly recommends to not lock project on specific GPL version.
Also see https://github.com/gkdr/libomemo/issues/10#issuecomment-290096780

**Comment by gkdr** [comment]
According to [an answer on StackExchange](https://opensource.stackexchange.com/questions/4534/how-to-apply-mit-license-in-the-github-repo-for-fully-free-project), headers are not necessary for the MIT license.
