### ISSUE TITLE
Segfault in omemo_devicelist_import

### ISSUE THREAD

**Issue by geobra** [gkdr/libomemo#19]
While porting lurch.c to shmoose (XMPP Client for SailfishOS), I encountered a Segfault in the function omemo_devicelist_import of libomeo.c

When I pass a pointer to a char array with content like:

         char * array = "<items node=\"eu.siacs.conversations.axolotl.devicelist\"> \
           <item id=\"COFFEEBABE\"> \
            <list xmlns=\"eu.siacs.conversations.axolotl\"> \
             <device id=\"1234567890\"></device> \
            </list> \
           </item> \
          </items>";

in the function, it crashes at
ret_val = strncmp(mxmlGetElement(item_node_p), ITEM_NODE_NAME, strlen(ITEM_NODE_NAME));

Using gdb, I figured out that the (items) node
items_node_p = mxmlLoadString((void *) 0, received_devicelist, MXML_NO_CALLBACK);
is successfull assigned. All required members of the struct are correct filled. The next call to

item_node_p = mxmlGetFirstChild(items_node_p);
returns a valid (item) node, but the needed members of the struct are not valid. Thus, the mentioned call to mxmlGetElement(item_node_p) results in a read of an uninitialized pointer, causes the segfault.

My testing environment is a Debian stable with libmxml 2.10. I also tried the 2.7 version, as mentioned in the readme of lurch. Same issue.

Any hints about that?

**Comment by gkdr** [comment]
If I remember correctly I sometimes encountered invalid pointer problems when using mxml when I modified the nodes in some way that I expected to propagate but it didn't. Maybe I did something stupid like that here too.
Is the string you gave me consistently producing the segfault?

**Comment by geobra** [comment]
Just want to make an minimal c example for you. During this I recognized that if I remove all the white spaces, it didn't crash. Let me dive again into this...

**Comment by geobra** [comment]
Okay, the problem is in libmxml. One have to pass a char* with no newline or whitspaces into it. Don't know if that is a bug or a feature ;-). I will close this issue now. Sorry for that.

**Comment by gkdr** [comment]
No worries, glad you found a solution.
